### PR TITLE
Updated to MacOSX 10.13 & Added ContentDescription

### PR DESCRIPTION
**Pull request by lvillacin**
## Changes
- Updated packages and code to work with MacOSX 10.13 and Node 16.
- Added contentDescription as an attribute.

## Contribution By
- @lvillacin from https://meetbit.io

### CODE REVIEW

**Comment by evanjmg** [comment]
I tried your branch  with macOS 11.4 , electron 20.1.0, electron rebuild 3.2.9 and get compiler errors when I try to rebuild with electron-rebuild on 107 node version 
tion.o
⠼ Building module: electron-spotlight, Completed: 0In file included from ../Integration.cc:1:
In file included from ../../nan/nan.h:180:
../../nan/nan_callbacks.h:55:23: error: no member named 'AccessorSignature' in namespace 'v8'
typedef v8::Local<v8::AccessorSignature> Sig;
                  ~~~~^
In file included from ../Integration.cc:1:
../../nan/nan.h:2546:8: error: no matching member function for call to 'SetAccessor'
  tpl->SetAccessor(
  ~~~~~^~~~~~~~~~~
/Users/evan.gillogley/.electron-gyp/20.1.0/include/node/v8-template.h:814:8: note: candidate function not viable: no known conversion from 'imp::Sig' (aka 'int') to 'v8::SideEffectType' for 7th argument
  void SetAccessor(
       ^
/Users/evan.gillogley/.electron-gyp/20.1.0/include/node/v8-template.h:807:8: note: candidate function not viable: no known conversion from 'imp::NativeGetter' (aka 'void (*)(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value> &)') to 'v8::AccessorGetterCallback' (aka 'void (*)(Local<v8::String>, const PropertyCallbackInfo<v8::Value> &)') for 2nd argument
  void SetAccessor(
       ^
⠴ Building module: electron-spotlight, Completed: 02 errors generated.
make: *** [Release/obj.target/Spotlight/Integration.o] Error 1
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild '/Users/evan.gillogley/dev/platform-ui-web/node_modules/electron-spotlight'.
For more information, rerun with the DEBUG environment variable set to "electron-rebuild".

Error: `make` failed with exit code: 2



Error: node-gyp failed to rebuild '/Users/evan.gillogley/dev/platform-ui-web/node_modules/electron-spotlight'.
For more information, rerun with the DEBUG environment variable set to "electron-rebuild".

Error: `make` failed with exit code: 2


    at NodeGyp.rebuildModule (/Users/evan.gillogley/dev/platform-ui-web/node_modules/electron-rebuild/lib/src/module-type/node-gyp.js:120:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ModuleRebuilder.rebuildNodeGypModule (/Users/evan.gillogley/dev/platform-ui-web/node_modules/electron-rebuild/lib/src/module-rebuilder.js:98:9)
    at async ModuleRebuilder.rebuild (/Users/evan.gillogley/dev/platform-ui-web/node_modules/electron-rebuild/lib/src/module-rebuilder.js:128:14)
    at async Rebuilder.rebuildModuleAt (/Users/evan.gillogley/dev/platform-ui-web/node_modules/electron-rebuild/lib/src/rebuild.js:149:13)
    at async Rebuilder.rebuild (/Users/evan.gillogley/dev/platform-ui-web/node_modules/electron-rebuild/lib/src/rebuild.js:112:17)
    at async /Users/evan.gillogley/dev/platform-ui-web/node_modules/electron-rebuild/lib/src/cli.js:158:9

**Comment by evanjmg** [comment]
ah might have found a workaround https://github.com/electron/electron/issues/35193 - it's nan

**Comment by evanjmg** [comment]
updating 
  "xcode_settings": {
      "OTHER_CPLUSPLUSFLAGS": ["-std=c++17", "-stdlib=libc++", "-mmacosx-version-min=10.13"],
      "OTHER_LDFLAGS": ["-framework CoreFoundation -framework CoreSpotlight -framework AppKit"],
    }
and using this nan fork works https://github.com/jkleinsc/nan/tree/remove_accessor_signature
